2024-01-09 12:50:44,119 [ERROR] Request details: IP=127.0.0.1, User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, Endpoint=home, Method=GET, URL=http://127.0.0.1:5000/
2024-01-09 12:50:44,120 [ERROR] An error occurred:
Traceback (most recent call last):
  File "/home/brandon/Desktop/flasksdk/env/lib/python3.8/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brandon/Desktop/flasksdk/env/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brandon/Desktop/flasksdk/env/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brandon/Desktop/flasksdk/env/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brandon/Desktop/flasksdk/env/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/brandon/Desktop/flasksdk/app.py", line 16, in home
    result = "2" + 2  # Intentional division by zero to trigger an error (replace with your actual code)
TypeError: can only concatenate str (not "int") to str
